example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
from django.urls import path
from katalog.views import katalog_view

# TODO: Implement Routings Here
app_name = 'katalog'

urlpatterns = [
    path('', katalog_view, name = 'katalog_view'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import watchlist_view
from mywatchlist.views import show_json
from mywatchlist.views import show_json_by_id
from mywatchlist.views import show_xml

# TODO: Implement Routings Here
app_name = 'mywatchlist'

urlpatterns = [
    path('', watchlist_view, name = 'watchlist_view'),
    path('html/', watchlist_view, name='watchlist_view'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'), 
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

todolist/urls.py
from django.urls import path
from todolist.views import show_todolist, register, login_user, logout_user,show_create_task, change, delete, show_json, add_todo_ajax

# TODO: Implement Routings Here
app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name = 'show_todolist'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', register, name='register'),
    path('create-task/', show_create_task, name='create_task'),
    path('delete/<int:pk>', delete, name='delete'),
    path('change/<int:pk>', change, name='change'),
    path('json/', show_json, name='show_json'),
    path('add/', add_todo_ajax, name='add_todo_ajax')
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

class WatchlistItem(models.Model):
    watched = models.BooleanField(max_length=255)
    title = models.TextField()
    release_date = models.DateField()
    rating = models.IntegerField(validators=[MaxValueValidator(5), 
                                             MinValueValidator(1)])
    review = models.TextField()

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

class TodoItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    title = models.CharField(max_length=100)
    description = models.TextField()
    finished = models.BooleanField(default=False, null=True, blank=True)

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

# TODO: Create views.
def katalog_view (request):
    catalogitem = CatalogItem.objects.all()
    context = {
    'list_item': catalogitem,
    'nama': 'Kaylee Rudaina Danisha',
    'id': '2106654971'
    }
    return render(request, "katalog.html", context)

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import WatchlistItem
from django.http import HttpResponse
from django.core import serializers

# TODO: Create views.
def watchlist_view (request):
    watchlistitem = WatchlistItem.objects.all()
    context = {
    'list_watchlist': watchlistitem,
    'nama': 'Kaylee Rudaina Danisha',
    'id': '2106654971'
    }
    return render(request, "mywatchlist.html", context)

def show_xml(request):
    data = WatchlistItem.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = WatchlistItem.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request, id):
    data = WatchlistItem.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = WatchlistItem.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

todolist/views.py
import datetime
from django.shortcuts import render
from todolist.models import TodoItem
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
@login_required(login_url='/todolist/login/')
def show_todolist (request):
    todo_item = TodoItem.objects.filter(user=request.user)
    context = {
    'list_todo': todo_item,
    'nama': 'Kaylee Rudaina Danisha',
    'username': request.user.username,
    }
    return render(request, "todolist.html", context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse("todolist:show_todolist"))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/todolist/login/')
def show_create_task(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('deskripsi')
        finished = False
        todo = TodoItem.objects.create(title=title, description=description, date=datetime.date.today(), user=request.user, finished=finished)
        response = HttpResponseRedirect(reverse("todolist:show_todolist"))
        return response
    return render(request, "create.html")

@csrf_exempt  
def delete(request, pk):
    TodoItem.objects.filter(id=pk).delete()
    return redirect('todolist:show_todolist')

def change(request, pk):
    data = TodoItem.objects.get(id=pk)
    data.is_finished = not(data.is_finished)
    data.save()
    return redirect('todolist:show_todolist')


@login_required(login_url='/todolist/login/')
def show_json(request):
    user = TodoItem.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', user), content_type='application/json')

@login_required(login_url='/todolist/login/')
def add_todo_ajax(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('deskripsi')
        finished = False
        todo = TodoItem.objects.create(title=title, description=description, date=datetime.date.today(), user=request.user, finished=finished)
        todo.save()
        
        result = {'fields': {
                        'title':todo.title,
                        'description':todo.description.title,
                        'date':todo.date,
                        'finished':todo.finished
                    },
                'pk':todo.pk
                }
        return JsonResponse(result, status=200)

                    

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{id}}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for item in list_item %}
      <tr>
        <th>{{item.item_name}}</th>
        <th>{{item.item_price}}</th>
        <th>{{item.item_stock}}</th>
        <th>{{item.rating}}</th>
        <th>{{item.description}}</th>
        <th>{{item.item_url}}</th>
      </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}
  <style>
    body {
    background-color: lightblue;
    }
    h1 {text-align: center;}
    h5 {text-align: center;}
    p {text-align: center;}
    table.center {
    margin-left:auto; 
    margin-right:auto;
    }
    table, th, td {
    border: 1px solid coral;
    }
    th, td {
    padding: 10px;
    }
  </style>
  <h1>Tugas 3 PBP</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{id}}</p>

  <table class="center">
    <tr>
      <th>Watched</th>
      <th>Movie Title</th>
      <th>Release Date</th>
      <th>Rating</th>
      <th>Review</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for item in list_watchlist %}
      <tr>
        <td>{{item.watched}}</td>
        <td>{{item.title}}</td>
        <td>{{item.release_date}}</td>
        <td>{{item.rating}}</td>
        <td>{{item.review}}</td>
      </tr>
    {% endfor %}
  </table>

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>

todolist/templates/create.html
{% extends 'base.html' %}

{% block meta %}
<title>To Do List</title>
{% endblock meta %}

{% block content %}

<div class = "create">

    <h1>Create new Task!</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Judul: </td>
                <td><input type="text" name="title" placeholder="Title" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Deskripsi: </td>
                <td><input type="text" name="deskripsi" placeholder="Deskripsi" class="form-control" size ="40"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Submit"></td>
            </tr>
        </table>
    </form>

</div>

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<style>
    .login {
        display:flex;
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }
    h1 {
    text-align: center;
    }
    body {
    background-color: rgb(195, 232, 255);
    font-family: Arial, Helvetica, sans-serif;
    }
    table.center{
      margin-left:auto;
      margin-right:auto;
    }
    table, th, td {
    border-collapse: collapse;
    }

    th, td {
    padding: 10px;
    }
</style>
<body>
<div class = "login h-auto">
    <div class="card text-white text-center bg-primary m-5 py-4" style="max-width: 20rem">
        <div class="card-body py-2">
            <h1 class="card-title">Login</h1>
            <form method="POST" action="">
                {% csrf_token %}
                <table>
                    <tr>
                        <td>Username: </td>
                        <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                    </tr>
                            
                    <tr>
                        <td>Password: </td>
                        <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                    </tr>
                </table>
                <input class="btn btn-light" type="submit" value="Login">
            </form>

            {% if messages %}
                <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}     
            <br>
            Belum mempunyai akun? <a href="{% url 'todolist:register' %}" class="btn btn-secondary">Buat Akun</a>
        </div>   
    </div>
</div>
</body>
{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  
<style>
    body {
    background-color: rgb(195, 232, 255);
    font-family: Arial, Helvetica, sans-serif;
    }
    th, td {
    padding: 10px;
    }
</style>
<body>
<p class="h1 text-center py-5"><strong>Formulir Registrasi</strong></p>  
<div class = "login d-flex justify-content-center">
        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
            </table>  
            <input class="btn login_btn btn-lg btn-primary col-12 my-3" type="submit" name="submit" value="Daftar"/>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  
</body>

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block content %}
<style>
    header {
    justify-content: flex-end;
    }
    body {
    background-color: rgb(195, 232, 255);
    font-family: Arial, Helvetica, sans-serif;
    }
    .wrapper {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    row-gap: 3px;
    column-gap: 3px; 
    }
    .card {
    margin-bottom: 20px;
    justify-content: center;
    color: rgb(13, 115, 253);
    }
    .card:hover {
      transform: translateY(-10px);
    }
</style>
<header>
    <nav class="navbar navbar-expand-lg navbar-light justify-content-between">
        <a class="navbar-brand" style="color: rgb(9, 114, 177);font-size: 30px;" href="#">To-do List {{user.username}}</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"><</span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="#" class="nav-link" data-bs-toggle="modal" type="submit" data-bs-target="#modalAdd">Create Task</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'todolist:logout' %}" class="nav-link" type="submit">Logout</a>
                </li>
            </ul>
        </div>
    </nav>
</header>
<br>
<body>
    <div class="d-flex justify-content-center my-4 text-center">
        <h2>❗ Here is your To-do, {{user.username}} ❗</h2>
    </div>
    {% comment %} Data dalam list_todo {% endcomment %}
    <div class="container"> </div>
    <form action="" method="POST" id="tambahTask">  
        {% csrf_token %} 
        <table>  
            <div class="modal fade" id="modalAdd" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h1 class="modal-title fs-5" id="staticModalLabel">Create New Todolist</h1>
                      <button type="button" class="button" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <input class="form-control" type="text" id="title" name="title" placeholder="Title" aria-label="Title" aria-describedby="basic-addon1">
                        <br>
                        <input class="form-control" type="text" id="description" name="description" placeholder="Description" aria-label="Description" aria-describedby="basic-addon1">
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
                      <button type="submit" class="btn btn-primary" data-bs-dismiss="modal" id="createButton" onclick="show_data()">Create</button>
                    </div>
                  </div>
                </div>
              </div>
        </table>
    </form>
<br>

<br>
</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    function show_card(){
    let todolist = "";
    $.ajax({
      url: "{% url 'todolist:show_json' %}", 
      type: "GET", 
      dataType: "json",
      success: function(data){
        for(i of data){
          let todoStatus = i.fields.finished ? "Done" : "On going";
          todolist += `
          <div class="card" style="width: 18rem; margin-right: auto; margin-left: auto; padding-bottom: 20; margin-top: 20px;">
            <div class="card-body">
              <h3 class="card-title">${i.fields.title}</h3>
              <h6 class="card-font">${i.fields.date}</h6>
              <p class="card-font">${i.fields.description}</p>
              <p class="card-text">${todoStatus}</p>
              <a class="btn login_btn" href="status_task/${i.id}">Ubah Status</a>
              <a class="btn login_btn"  type="submit" onclick="deleteTask(${i.pk})">Hapus</a>
            </div>
          </div>`;
          $('#container').html(todolist)
        }
      },
      error: function(data) {
        console.log('Error')
      }
    })
  }

  function deleteTask(pk){
        $.ajax({
            url: `/todolist/delete/${pk}`,
            type: "DELETE",
            success: function(data) {
                $(`#${pk}`).remove()
                show_card()
            }
        })
    }
  
  function show_data(){
    $.ajax({
      url: "{% url 'todolist:add_todo_ajax' %}", 
      type: "POST", 
      dataType:"json",
      data: {
        title:$("#title").val(),
        description:$("#description").val(),
        csrfmiddlewaretoken: "{{ csrf_token }}"
      },
    success: function(data) {
      show_card();
      const inputs = document.querySelectorAll('#title, #description');
      inputs.forEach(input => {
        input.value = '';
      });
    }
    })
  }

  $(document).ready(function () {
    show_card();
  })
</script>

{% endblock content %}